update Docckerfile
soramitsu/iroha2-block-explorer-web pull request #12
Opened 2022-05-17 10:03 UTC by BAStos525

# Task
[DOPS-1741]: Deploy Iroha2 Block Explorer testing env

## Changes
Switch to unprevilidge nginx container and update Dockerfile according to it

## Author
Sign-by-off: Vasilii Zyabkin <zyabkin@soramitsu.co.jp>

[DOPS-1741]: https://soramitsu.atlassian.net/browse/DOPS-1741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-05-18 00:59 UTC, wpi86 requested changes

2022-05-18 00:59 UTC, wpi86 commented on Dockerfile
> +    chown -R iroha ${LOAD_DIR}
Best practice is not to do this, as executables should be immutable to reduce the attack surface. I think you should give minimum sufficient permissions

2022-05-18 10:29 UTC, Cre-eD commented on Dockerfile
> +RUN mkdir -p ${LOAD_DIR} && \
I see no sense, you create a folder as root, but then change permissions

2022-05-30 09:23 UTC, Cre-eD reviewed
don't use `node:latest` specify version

2022-06-02 20:55 UTC, Cre-eD approved these changes

2022-06-03 14:26 UTC, merged